version: '3'

networks:
  host:

services:
  postgres:
    container_name: postgres
    image: oseberg/postgres:1.3-12
    ports:
      - 5432:5432
    networks:
      - host
    environment:
      POSTGRES_DB: demo_dev
      POSTGRES_PASSWORD: postgres
    shm_size: 1g
